PR
PixxieBot/docs pull request #3
Opened 2023-12-04 18:09 UTC by Fellintron

- [x] PR marriage and setup (old images)
- [ ] Replace old images with new images
- [ ] add hints
- [ ] Deprecate mentions of `prefix` use slash commands instead
- [ ] new gif for `/imagelock`
- [ ] Premium perks mention
- [ ] Rename Files
- [ ] Remove out-dated hyperlinks and link them to new ones
- [ ] Fix some features in `Summary`

2023-12-04 18:52 UTC, pixxies requested changes
Looking good! Off to a great start! 🙏

2023-12-04 18:52 UTC, pixxies commented on docs/features/profiles/marriages/divorcing.md
> -This second method is especially useful if the person you want to divorce no longer shares any mutual servers with you or has deleted their account.
It's important to mention this is how you divorce someone who isn't in the server. People ask this all the time

2023-12-04 18:52 UTC, pixxies commented on docs/features/profiles/marriages/marrying.md
> +To cancel a marriage proposal you have made to someone, use `/marry cancel <fiancé>`.
Here `fiancé` is optional so `[fiancé]`. Running it without the fiancé will give you a dropdown like for divorcing someone off-server.

2023-12-04 18:52 UTC, pixxies commented on docs/features/profiles/marriages/marrying.md
> +To reject a proposal someone has made to you, do `/marry decline <user>`.
User is also optional here and gives a dropdown

2023-12-05 09:23 UTC, pixxies commented
You'll need to add "dropdown" to the `custom-dictionary.txt` file in`.github` and any other words that fail the spellcheck workflow.

2024-01-17 18:11 UTC, Fellintron commented
tf so many spellcheck fails 💀 gotta add them

2024-01-17 18:23 UTC, Fellintron commented
hello?????? 
![image](https://github.com/PixxieBot/docs/assets/77188942/088f89ff-2e39-4f95-80ba-d0b4f4f6a98b)

2024-01-17 18:35 UTC, Fellintron commented
YESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS ALL CHECKS HAVE BEEN PASSED

2024-01-25 17:09 UTC, Fellintron commented
You have to edit refunds clause under terms of use, i think that's all

2024-01-29 10:52 UTC, pixxies approved these changes, later dismissed

2024-01-29 10:52 UTC, pixxies commented on docs/features/profiles/marriages/current-marriages.md
>  ![](../../../.gitbook/assets/married.jpg)
This image is missing from this PR

2024-01-29 10:53 UTC, pixxies commented on docs/features/profiles/marriages/current-marriages.md
>  ![](../../../.gitbook/assets/married.jpg)
@Fellintron We just need this and then we're good to go! :)

2024-01-29 14:52 UTC, pixxies approved these changes

2024-01-29 14:53 UTC, merged